### ISSUE TITLE
info

### ISSUE THREAD

**Issue by AntiWarforever** [Praveensenpai/bumsBot#1]
do task and upgrade card? or daily combo?

**Comment by Praveensenpai** [comment]
Right now, it only upgrades cards, taps for me, and does the daily check-in. It doesn’t handle tasks yet since the API doesn’t seem to be working.

**Comment by Praveensenpai** [comment]
Also it only upgrade card which is most profitable.

**Comment by AntiWarforever** [comment]
you can made multi threading with multi account?

**Comment by Praveensenpai** [comment]
Some features aren't working properly right now; I'll look into adding multiple accounts after I fix those.
