### ISSUE TITLE
ERROR - {'code': 0,

### ISSUE THREAD

**Issue by primushkodenis** [Praveensenpai/bumsBot#4]
WARNING - Failed to claim daily reward
ERROR - {'code': 0, 'msg': 'OK', 'data': {'lists': [{'days': 1, 'daysDesc': 'Day 1', 'normal': 10000, 'premium': 0, 'status': 0, 'adId': 0, 'bigDay': 0}, {'days': 2, 'daysDesc': 'Day 2', 'normal': 20000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 3, 'daysDesc': 'Day 3', 'normal': 30000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 4, 'daysDesc': 'Day 4', 'normal': 40000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 5, 'daysDesc': 'Day 5', 'normal': 50000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 6, 'daysDesc': 'Day 6', 'normal': 60000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 7, 'daysDesc': 'Day 7', 'normal': 80000, 'premium': 200010001, 'status': 2, 'adId': 0, 'bigDay': 1}, {'days': 8, 'daysDesc': 'Day 8', 'normal': 100000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 9, 'daysDesc': 'Day 9', 'normal': 200000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 10, 'daysDesc': 'Day 10', 'normal': 300000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 11, 'daysDesc': 'Day 11', 'normal': 400000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 12, 'daysDesc': 'Day 12', 'normal': 500000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 13, 'daysDesc': 'Day 13', 'normal': 600000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 14, 'daysDesc': 'Day 14', 'normal': 800000, 'premium': 200010002, 'status': 2, 'adId': 0, 'bigDay': 1}, {'days': 15, 'daysDesc': 'Day 15', 'normal': 1000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 16, 'daysDesc': 'Day 16', 'normal': 2000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 17, 'daysDesc': 'Day 17', 'normal': 3000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 18, 'daysDesc': 'Day 18', 'normal': 4000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 19, 'daysDesc': 'Day 19', 'normal': 5000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 20, 'daysDesc': 'Day 20', 'normal': 6000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 21, 'daysDesc': 'Day 21', 'normal': 8000000, 'premium': 200010003, 'status': 2, 'adId': 0, 'bigDay': 1}, {'days': 22, 'daysDesc': 'Day 22', 'normal': 10000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 23, 'daysDesc': 'Day 23', 'normal': 20000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 24, 'daysDesc': 'Day 24', 'normal': 30000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 25, 'daysDesc': 'Day 25', 'normal': 40000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 26, 'daysDesc': 'Day 26', 'normal': 50000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 27, 'daysDesc': 'Day 27', 'normal': 60000000, 'premium': 0, 'status': 2, 'adId': 0, 'bigDay': 0}, {'days': 28, 'daysDesc': 'Day 28', 'normal': 80000000, 'premium': 200010004, 'status': 2, 'adId': 0, 'bigDay': 1}], 'signNum': 1, 'signStatus': 0}}

**Comment by Praveensenpai** [comment]
I guess the daily claim api doesn't seem to work. I guess I have to find out tomorrow. For now u can manually sign in so u don't get the error.

**Comment by Praveensenpai** [comment]
fixed
