### ISSUE TITLE
refferal dont work.

### ISSUE THREAD

**Issue by faerhjio0gase** [Praveensenpai/bumsBot#8]

**Comment by Praveensenpai** [comment]
what u mean? can u be more specific

**Comment by faerhjio0gase** [comment]
i add my ref to env and run script. but refferals dont added in game

**Comment by Praveensenpai** [comment]
I don't understand what you mean by referrals not adding in the game.  

Are you expecting referrals to count? If so, just to clarify, the referral ID is only used to start the bot and doesn't increase your referral count.
